# .github/workflows/final-pipeline.yaml

name: Final End-to-End CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: BUILD AND PUSH THE DOCKER IMAGE ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Use the 'Backend' folder as the context, matching your structure
          context: ./Backend
          push: true
          # IMPORTANT: Use your Docker Hub username here
          tags: kisakitetta/fadeaway-backend:${{ github.sha }}

  # --- JOB 2: DEPLOY TO KUBERNETES CLUSTER ---
  deploy:
    # This job will only run after 'build-and-push' succeeds
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your preferred region

      - name: Configure Kubectl for EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name fade-away-cluster
          kubectl config get-contexts

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/fade-away-chat-deployment fade-away-chat-container=kisakitetta/fadeaway-backend:${{ github.sha }}